### ISSUE TITLE
How much GPU memory is used in typical calculation?

### ISSUE THREAD

**Issue by alpha358** [disordered-photonics/celes#11]
Hello, I am trying to decide which nvidia gpu to buy.
Roughly how many particles can I simulate using 3GB gpu ram with default settings ?

**Comment by lpattelli** [comment]
Hi,
typically GPU memory is not the limiting factor for large simulations.
In case you have densely packed particles you might want to use preconditioner for faster convergence, but then your limiting factor would probably be main memory rather than GPU memory.
So my advice is to prefer high number of CUDA cores over large GPU memory.

As a quick example: I just tried to start a 10k-particles simulation on my old laptop mounting a GeForce GT 650M (2GB memory, 384 CUDA cores), which runs just fine but takes ~160s/iteration. However, if I turn on preconditioning, I have to keep the partitions small enough to avoid filling my 16GB main RAM.

hope this helps!
Lorenzo
