### ISSUE TITLE
Questions about CELES

### ISSUE THREAD

**Issue by AC-One** [disordered-photonics/celes#30]
Dear Drs. Egel and Pattelli,

I learned about CELES through your 2017 publication titled ‘ CELES: CUDA-accelerated simulation of electromagnetic scattering by large ensembles of spheres.’ Since my research involves studying the diffraction patterns generated by organized particles, I am very interested in using CELES to confirm some of my experimental outcomes. 

Over the past week, I was able to install CELES correctly and ran some trial simulations. However, I do have a few questions about CELES, which I hope you can answer for me.  

(1)	Can CELES be used for a single scatterer? I want to perform a comparison between CELES and Mie Scattering theory.
(2)	Is the unit of all dimensional parameters (e.g., particle radius) nm?
(3)	Is it possible to implement a collimated beam (not focused) with a finite diameter? If so, could you please advise how I may do it?
(4)	Is there an up limit regarding the number of scatterers? In your article (figure 6), you mentioned it is possible to simulate 10^5 particles. 
(5)	Your article mentioned that CELES could simulate the E field in the far-field. Would it be possible to study the scattered E field, for example, 10 cm away from the scatterer cluster?

I look forward to hearing from you soon.

WC Lin
wclin@fiu.edu
Florida International University

**Comment by lpattelli** [comment]
Dear Prof. Lin,

thank you for your interest. I'll try to address the questions you raised, then perhaps Amos can add more details if I made some mistake or forgot something relevant

1) Yes, you can run a calculation for a single particle. Computationally, since CELES relies on the GPU, this would not be very efficient for such a small number of particles, but I think that the runtime would still be very fast and not much of a concern for a validation test.
2) Any unit of measurement can be used, as long as all parameters (particle radii, positions, lookup table resolution, plotting grid, wavelength, etc.) are defined using the same units.
3) I may be wrong, but I think that it is not possible to simulate a perfectly collimated beam, which would be unphysical. However, by setting a rather large beam waist, I think you should get a very gentle focus resulting in a long Rayleigh length.
4) Practical limits on the number of scatterers exist and are mostly dictated by memory requirements and total runtime. In general, if the particles are much smaller than the wavelength, they can be described using only a few terms in the multipolar expansion (e.g., lmax = 1 or 2), which would probably let you simulate more than 1E5 particles in a reasonable time. When more multipolar terms are needed (i.e., for large particles or densely packed particle aggregates), the iterative solver could take extremely long times to converge to a solution. Turning on a preconditioner can help (especially at high particle densities), but then the memory requirements grow a lot - so there's always a tradeoff.
5) In CELES, we typically refer to the "far field" as a representation of the power scattered as a function of angle in the forward and backward hemispheres, and to the "near field" as a representation of the electric field as a function of position (not necessarily "near" to the particles). Then I guess that you could try to print the near field at such a large distance from the particle aggregate, but perhaps what you are really interested in at such a large distance is the far field as a function of the angle, rather than the direct field distribution as a function of position.

Hope this answer your questions (if so, let us know so that we can close the issue),
Cheers,
Lorenzo

**Comment by lpattelli** [comment]
One more thing: if you did not do so already, I suggest that you check out the most recent code available on the [tiltedPWs](https://github.com/disordered-photonics/celes/tree/tiltedPWs) branch and run the updated `CELES_MAIN.m` script that you can find there, which shows some extra quantities that can also be plotted with CELES.

**Comment by AC-One** [comment]
Dear Dr. Pattelli,

Thank you for your quick response and for answering my questions. I will
follow your suggestions to set up CELES for my research work. Regarding my
post on Github, you can indicate it has been resolved.

I shall contact you directly when I have additional questions. Also, I
shall acknowledge your contribution in my publications related to this work.

Best,

Wei-Chiang Lin
Department of Biomedical Engineering
Florida International University
***@***.***
