### ISSUE TITLE
Is this project maintaining?

### ISSUE THREAD

**Issue by ehgus** [disordered-photonics/celes#32]
The code has a margin to improve the performance, but I saw that the PR and issue response had been stopped since 2020.
Would you be able to take my potential PRs and update this solver?

**Comment by AmosEgel** [comment]
Dear Dohyeon, yes - this project is not actively developed by the original crew. But nevertheless, we are still there and if you want to add some functionality, we will be glad to receive your merge requests. I cannot test anything, because I don't have Matlab anymmore. But I think @lpattelli still has access.

So in case you want to add a feature, please start from an issue such that we can give our five cents. 

Welcome on board :)

**Comment by ehgus** [comment]
I am very happy with your reply. thanks!
